SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `article`;
DROP TABLE IF EXISTS `log`;
DROP TABLE IF EXISTS `review`;
DROP TABLE IF EXISTS `tag`;
DROP TABLE IF EXISTS `test`;
DROP TABLE IF EXISTS `topic`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `usergroup`;
CREATE TABLE `article` (`aid` int(11) NOT NULL AUTO_INCREMENT,`title` varchar(64) NOT NULL,`content` varchar(5120) NOT NULL,`uid` int(11) NOT NULL,`time` datetime NOT NULL,`state` tinyint(4) NOT NULL DEFAULT '0',PRIMARY KEY (`aid`)) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
CREATE TABLE `log` (`session_id` varchar(32) COLLATE utf8mb4_bin NOT NULL,`uid` int(11) DEFAULT NULL,`api` varchar(16) COLLATE utf8mb4_bin NOT NULL,`handle` varchar(64) COLLATE utf8mb4_bin NOT NULL,`url` varchar(256) COLLATE utf8mb4_bin DEFAULT NULL,`errCode` int(11) DEFAULT NULL,`errMsg` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,`time` datetime NOT NULL,`rand` int(11) NOT NULL,`ip` char(15) COLLATE utf8mb4_bin NOT NULL,PRIMARY KEY (`session_id`,`api`,`handle`,`time`,`rand`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `review` (`rid` int(11) NOT NULL AUTO_INCREMENT,`tid` int(11) NOT NULL,`uid` int(11) NOT NULL,`content` varchar(2048) COLLATE utf8mb4_bin NOT NULL,`time` datetime NOT NULL,`state` tinyint(4) NOT NULL DEFAULT '0',PRIMARY KEY (`rid`),KEY `tid` (`tid`),KEY `uid` (`uid`)) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `tag` (`tag_id` int(11) NOT NULL,`name` varchar(32) COLLATE utf8mb4_bin NOT NULL,`belong` int(11) DEFAULT NULL,PRIMARY KEY (`tag_id`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `test` (`key` varchar(256) NOT NULL,`value` varchar(256) NOT NULL,PRIMARY KEY (`key`)) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE `topic` (`tid` int(11) NOT NULL AUTO_INCREMENT,`content` varchar(2048) COLLATE utf8mb4_bin NOT NULL,`uid` int(11) NOT NULL,`time` datetime NOT NULL,`area_id` varchar(6) COLLATE utf8mb4_bin NOT NULL,`tag_id` int(11) NOT NULL,`image` varchar(1024) COLLATE utf8mb4_bin DEFAULT '[]',`is_top` tinyint(4) NOT NULL DEFAULT '0',`top_time` datetime DEFAULT NULL,`state` tinyint(4) NOT NULL DEFAULT '0',PRIMARY KEY (`tid`),KEY `tagid` (`tag_id`),KEY `uid` (`uid`)) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `user` (`uid` int(11) NOT NULL AUTO_INCREMENT,`usr` varchar(12) COLLATE utf8mb4_bin NOT NULL,`pwd` varchar(32) COLLATE utf8mb4_bin NOT NULL,`avatar` varchar(128) COLLATE utf8mb4_bin DEFAULT NULL,`nickname` varchar(16) COLLATE utf8mb4_bin DEFAULT NULL,`phone` char(11) COLLATE utf8mb4_bin NOT NULL,`gender` tinyint(4) NOT NULL DEFAULT '0',`birth` date DEFAULT '1990-01-01',`ugid` int(11) NOT NULL,`area_id` varchar(6) COLLATE utf8mb4_bin NOT NULL,`wechat_openid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,`wechat_unionid` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,`last_area` varchar(6) COLLATE utf8mb4_bin NOT NULL,`last_time` datetime NOT NULL,`reg_area` varchar(6) COLLATE utf8mb4_bin NOT NULL,`reg_time` datetime NOT NULL,`state` tinyint(4) NOT NULL DEFAULT '0',PRIMARY KEY (`uid`),UNIQUE KEY `usr` (`usr`),KEY `ugid` (`ugid`)) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
CREATE TABLE `usergroup` (`api` varchar(64) NOT NULL,`handle` varchar(64) NOT NULL,`0` tinyint(4) NOT NULL DEFAULT '0',`1` tinyint(4) NOT NULL DEFAULT '0',`9` tinyint(4) NOT NULL DEFAULT '0',PRIMARY KEY (`api`,`handle`)) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
INSERT INTO `user`VALUES('1', 'admin', '123456', null, 'admin', '17615168826', '0', '1998-06-29', '9', '1', '', '', '1', '2021-01-01 12:00:00', '1', '2021-01-01 12:00:00', '0');
INSERT INTO `usergroup` VALUES ('user', 'login', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('user', 'reg', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('user', 'edit', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('user', 'logout', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('user', 'profile', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('topic', 'list', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('topic', 'read', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('topic', 'add', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('topic', 'del', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('review', 'list', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('review', 'read', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('review', 'add', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('review', 'del', '0', '1', '1');
INSERT INTO `usergroup` VALUES ('article', 'list', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('article', 'read', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('article', 'add', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('article', 'del', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('tag', 'list', '1', '1', '1');
INSERT INTO `usergroup` VALUES ('admin', 'user', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'topic', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'review', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'status', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'site', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'article', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('admin', 'login', '0', '0', '1');
INSERT INTO `usergroup` VALUES ('test', '', '0', '0', '0');
INSERT INTO `tag` VALUES ('0', '广场', null);
INSERT INTO `test` VALUES ('test', '123');
INSERT INTO `test` VALUES ('hello', '123');